<a href="https://colab.research.google.com/github/AngryWeassel/Proyecto_Tasa_de_Natalidad.ipynb/blob/main/Proyecto_Tasa_de_Natalidad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import gdown
import pandas as pd
import matplotlib.pyplot as plt

#Importación de lista de Paises de la OCDE (En ingles OECD)
#Fuente: Consulta en Google y creación de Excel manual
archivo_nombres_ocde = 'https://docs.google.com/spreadsheets/d/1gpatuWv1C5Iq14sTngbqZV01PtK4T-1VuIty43tDE58/edit?usp=drive_link'
nombres_ocde = gdown.download(archivo_nombres_ocde, quiet=True, fuzzy=True)
ocde = pd.read_excel(nombres_ocde)

#Importación de datos del PIB de los paises a nivel global
#Fuente:
archivo_pib = 'https://drive.google.com/file/d/1RWhkgYFs73Ya0XUdyNmeo8IZ7yLC7mxG/view?usp=sharing'
pib = gdown.download(archivo_pib, quiet=True, fuzzy=True)
datos_pib = pd.read_csv(pib)

#Importación de datos de las edades de retiro (pensión) de los paises de la OCDE por cada hoja (hoja "Hombres" y hoja "Mujeres")
#Fuente:
archivo_pensiones = 'https://docs.google.com/spreadsheets/d/1xEL0RQ5GfFZG0gBU6bYaIjlXI3QUtN6hni_eN4HLuBk/edit?usp=sharing'
pensiones_descarga = gdown.download(archivo_pensiones, quiet=True, fuzzy=True)
pensiones_hombres = pd.read_excel(pensiones_descarga, sheet_name='Hombres')
pensiones_mujeres = pd.read_excel(pensiones_descarga, sheet_name='Mujeres')

In [2]:
diccionario_paises = {
    'Alemania': 'Germany',
    'Australia': 'Australia',
    'Austria': 'Austria',
    'Bélgica': 'Belgium',
    'Canadá': 'Canada',
    'Chile': 'Chile',
    'Colombia': 'Colombia',
    'Corea del Sur': 'South Korea',
    'Costa Rica': 'Costa Rica',
    'Dinamarca': 'Denmark',
    'Eslovenia': 'Slovenia',
    'España': 'Spain',
    'Estados Unidos': 'United States',
    'Estonia': 'Estonia',
    'Finlandia': 'Finland',
    'Francia': 'France',
    'Grecia': 'Greece',
    'Hungría': 'Hungary',
    'Irlanda': 'Ireland',
    'Islandia': 'Iceland',
    'Israel': 'Israel',
    'Italia': 'Italy',
    'Japón': 'Japan',
    'Letonia': 'Latvia',
    'Lituania': 'Lithuania',
    'Luxemburgo': 'Luxembourg',
    'México': 'Mexico',
    'Noruega': 'Norway',
    'Nueva Zelanda': 'New Zealand',
    'Países Bajos': 'Netherlands',
    'Polonia': 'Poland',
    'Portugal': 'Portugal',
    'Reino Unido': 'United Kingdom',
    'República Checa': 'Czechia',
    'República Eslovaca': 'slovakia',
    'Suecia': 'Sweden',
    'Suiza': 'Switzerland',
    'Turquía': 'Turkey'
}
ocde['OECD Countries'] = ocde['Paises OCDE'].map(diccionario_paises)
inv_diccionario_paises = {v: k for k, v in diccionario_paises.items()}

In [14]:
ocde

           Paises OCDE  OECD Countries
0             Alemania         Germany
1            Australia       Australia
2              Austria         Austria
3              Bélgica         Belgium
4               Canadá          Canada
5                Chile           Chile
6             Colombia        Colombia
7        Corea del Sur     South Korea
8           Costa Rica      Costa Rica
9            Dinamarca         Denmark
10           Eslovenia        Slovenia
11              España           Spain
12      Estados Unidos   United States
13             Estonia         Estonia
14           Finlandia         Finland
15             Francia          France
16              Grecia          Greece
17             Hungría         Hungary
18             Irlanda         Ireland
19            Islandia         Iceland
20              Israel          Israel
21              Italia           Italy
22               Japón           Japan
23             Letonia          Latvia
24            Lituania       Lithuania
25          Luxemburgo      Luxembourg
26              México          Mexico
27             Noruega          Norway
28       Nueva Zelanda     New Zealand
29        Países Bajos     Netherlands
30             Polonia          Poland
31            Portugal        Portugal
32         Reino Unido  United Kingdom
33     República Checa         Czechia
34  República Eslovaca        slovakia
35              Suecia          Sweden
36               Suiza     Switzerland
37             Turquía          Turkey

In [3]:
datos_pib = datos_pib.rename(columns={'Entity' : 'pais', 'Year' : 'año','GDP per capita': 'pib por pais', 'World region according to OWID' : 'continente'})
datos_pib.drop('Code', axis=1)

             pais   año  pib por pais continente
0     Afghanistan  2000     1617.8264       Asia
1     Afghanistan  2001     1454.1108       Asia
2     Afghanistan  2002     1774.3087       Asia
3     Afghanistan  2003     1815.9282       Asia
4     Afghanistan  2004     1776.9182       Asia
...           ...   ...           ...        ...
7235     Zimbabwe  2020     4527.7197     Africa
7236     Zimbabwe  2021     4827.0890     Africa
7237     Zimbabwe  2022     5036.7610     Africa
7238     Zimbabwe  2023     5218.0225     Africa
7239     Zimbabwe  2024     5215.2530     Africa

[7240 rows x 4 columns]

In [4]:
lista_ocde = ocde['OECD Countries'].tolist()

ocde_pib = datos_pib[
    (datos_pib['pais'].isin(lista_ocde)) &
    (datos_pib['año'] >= 2008) &
    (datos_pib['año'] <= 2024)
]

ocde_pib['pais español'] = ocde_pib['pais'].map(inv_diccionario_paises)

/tmp/ipykernel_6452/1363061585.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ocde_pib['pais español'] = ocde_pib['pais'].map(inv_diccionario_paises)

In [5]:
datos_pib

             pais Code   año  pib por pais continente
0     Afghanistan  AFG  2000     1617.8264       Asia
1     Afghanistan  AFG  2001     1454.1108       Asia
2     Afghanistan  AFG  2002     1774.3087       Asia
3     Afghanistan  AFG  2003     1815.9282       Asia
4     Afghanistan  AFG  2004     1776.9182       Asia
...           ...  ...   ...           ...        ...
7235     Zimbabwe  ZWE  2020     4527.7197     Africa
7236     Zimbabwe  ZWE  2021     4827.0890     Africa
7237     Zimbabwe  ZWE  2022     5036.7610     Africa
7238     Zimbabwe  ZWE  2023     5218.0225     Africa
7239     Zimbabwe  ZWE  2024     5215.2530     Africa

[7240 rows x 5 columns]

In [23]:
len(lista_ocde)

38

In [ ]:
pais_gdp_sum = gdp_oecd.groupby('Pais')['PIB por pais'].mean()
plt.figure(figsize=(20, 10))
pais_gdp_sum.plot(kind='bar', color='skyblue')
plt.title('Promedio total PIB por pais (2014-2024) [OECD]')
plt.xlabel('Pais')
plt.ylabel('Total PIB por pais (suma en miles de dolares $)')
plt.xticks(rotation=75, fontsize=9)
plt.grid(axis='y', linestyle='--', alpha=0.7)

overall_gdp_average = gdp_oecd['PIB por pais'].mean()

plt.axhline(y=overall_gdp_average, color='gray', linestyle='--', label=f'Total Promedia PIB [OCDE]: {overall_gdp_average:,.0f}')

for index, value in enumerate(pais_gdp_sum):
    plt.text(index, value + (max(pais_gdp_sum) * 0.0005), f'{value:,.0f}', ha='center', va='bottom', fontsize=8)

plt.legend()
plt.tight_layout()
plt.show()